Added Alchemy Support to the README Page
web3j/web3j pull request #1352
Opened 2021-01-25 23:16 UTC by smudgil

### What does this PR do?
This PR adds Alchemy to the list of supported features on the README page.

### Where should the reviewer start?
Look at the README page, under the Features section

### Why is it needed?
Web3 users can use Alchemy as a remote node provider

2021-01-26 11:41 UTC, conor10 requested changes

2021-01-26 11:41 UTC, conor10 commented on README.md
> +-   Support for [Alchemy](https://docs.alchemyapi.io/alchemy/guides/getting-started#web-3-j), so you don't have to run an Ethereum client yourself
Please can you  put Alchemy and Infura on the same line so we're not repeating ourselves?

2021-01-26 17:13 UTC, smudgil reviewed
Consolidated support for Alchemy and Infura in the same line

2021-02-22 10:03 UTC, conor10 requested changes
Please can you also add this to the Web3j docs too and I'll merge. https://github.com/web3j/web3j-docs

2021-02-22 23:37 UTC, smudgil commented
> Please can you also add this to the Web3j docs too and I'll merge. https://github.com/web3j/web3j-docs

just updated it! :)

2021-03-10 10:43 UTC, conor10 approved these changes

2021-03-10 10:43 UTC, merged