JSON-RPC error details
web3j/web3j pull request #1532
Opened 2021-11-02 00:59 UTC by dparmar

### What does this PR do?
It encapsulates all fields in JSON-RPC error into an Exception so that they are available to the caller.

### Where should the reviewer start?
[issue 1531](https://github.com/web3j/web3j/issues/1531)

### Why is it needed?
Fix for [issue 1531](https://github.com/web3j/web3j/issues/1531)

2021-12-13 15:24 UTC, SweeXordious requested changes
LGTM. 
Please add a test for this functionality then we will gladly merge.

2021-12-13 21:51 UTC, dparmar commented
> LGTM. Please add a test for this functionality then we will gladly merge.

Thanks for reviewing. I've added a unit test.

2021-12-14 08:39 UTC, SweeXordious approved these changes

2021-12-15 00:44 UTC, SweeXordious commented
I'll ask the team if we want this for this release or the upcoming release then come back to you.
Thanks for your contribution.

2022-02-03 11:18 UTC, merged