StaticStruct Method Signature Is Wrong
web3j/web3j pull request #1862
Opened 2023-02-03 18:55 UTC by txgyy

### What does this PR do?
*required*
if a function's parameter  like this, the function signature will be wrong,
```
public class Config extends StaticStruct {

    private final Address entryPoint;

    private final Address aggregator;

    private final StaticArray4<Uint256> publicKey;

    public Config(Address entryPoint, Address aggregator, StaticArray4<Uint256> publicKey) {
        super(entryPoint, aggregator, publicKey);
        this.entryPoint = entryPoint;
        this.aggregator = aggregator;
        this.publicKey = publicKey;
    }
}
```

### Where should the reviewer start?
org/web3j/abi/datatypes/StaticStruct.java:41
### Why is it needed?
*required*
it's a bug

2023-02-21 10:13 UTC, NickSneo requested changes

2023-02-21 10:13 UTC, NickSneo commented on abi/src/main/java/org/web3j/abi/datatypes/StaticStruct.java
> +            if (StructType.class.isAssignableFrom(cls) || Array.class.isAssignableFrom(cls)) {
Plz add a test case also as mentioned in description for this

2023-02-21 10:13 UTC, NickSneo commented on gradle.properties
> +version=4.9.6
No need to remove SNAPSHOT

2023-02-21 14:07 UTC, gtebrean commented
build is failing. Please run build locally first

2023-02-22 02:22 UTC, txgyy commented
> 

done

2023-02-22 06:44 UTC, NickSneo approved these changes

2023-02-22 10:26 UTC, merged